# Generated by Django 2.1 on 2018-08-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RC', 'Request Created'), ('PC', 'Partially Completed'), ('CO', 'Completed'), ('DE', 'Delivered')], default='RC', max_length=3)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='supplies_tracker.Volunteer')),
                ('delivery_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Center')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='supplies_tracker.Volunteer')),
            ],
            options={
                'verbose_name': 'ShipmentRequest',
                'verbose_name_plural': 'ShipmentRequests',
            },
        ),
        migrations.CreateModel(
            name='ShipmentRequestManifest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('RC', 'Request Created'), ('PC', 'Partially Completed'), ('CO', 'Completed'), ('DE', 'Delivered')], default='RC', max_length=3)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.InventoryItem')),
                ('shipment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Volunteer')),
            ],
            options={
                'verbose_name': 'ShipmentRequestManifest',
                'verbose_name_plural': 'ShipmentRequestManifests',
            },
        ),
        migrations.CreateModel(
            name='ShipmentRequestManifestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty_promised', models.IntegerField()),
                ('status_changed_to', models.CharField(choices=[('RC', 'Request Created'), ('PC', 'Partially Completed'), ('CO', 'Completed'), ('DE', 'Delivered')], default='RC', max_length=3)),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Volunteer')),
                ('shipment_request_manifest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.ShipmentRequestManifest')),
            ],
            options={
                'verbose_name': 'ShipmentRequestManifestLog',
                'verbose_name_plural': 'ShipmentRequestManifestLogs',
            },
        ),
    ]
