# Generated by Django 2.1 on 2018-08-19 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0003_auto_20180819_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItemStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_available', models.IntegerField(default=0)),
                ('qty_needed', models.IntegerField()),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('public_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Center')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.InventoryItem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Volunteer')),
            ],
            options={
                'verbose_name_plural': 'InventoryItemStock',
                'verbose_name': 'InventoryItemStock',
            },
        ),
        migrations.CreateModel(
            name='InventoryItemStockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_available', models.IntegerField()),
                ('qty_needed', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('inventory_item_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.InventoryItemStock')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Volunteer')),
            ],
            options={
                'verbose_name_plural': 'InventoryItemStockLogs',
                'verbose_name': 'InventoryItemStockLog',
            },
        ),
    ]
