# Generated by Django 2.1 on 2018-08-19 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0002_shipmentrequest_shipmentrequestmanifest_shipmentrequestmanifestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentRequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_item', models.TextField(blank=True, null=True)),
                ('qty', models.IntegerField()),
                ('status', models.CharField(choices=[('RC', 'Request Created'), ('PC', 'Partially Completed'), ('CO', 'Completed'), ('DE', 'Delivered')], default='RC', max_length=3)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.InventoryItem')),
                ('shipment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Volunteer')),
            ],
            options={
                'verbose_name': 'ShipmentRequestItem',
                'verbose_name_plural': 'ShipmentRequestItems',
            },
        ),
        migrations.CreateModel(
            name='ShipmentRequestItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('qty_promised', models.IntegerField()),
                ('status_changed_to', models.CharField(choices=[('RC', 'Request Created'), ('PC', 'Partially Completed'), ('CO', 'Completed'), ('DE', 'Delivered')], default='RC', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Volunteer')),
                ('shipment_request_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.ShipmentRequestItem')),
            ],
            options={
                'verbose_name': 'ShipmentRequestItemLog',
                'verbose_name_plural': 'ShipmentRequestItemLogs',
            },
        ),
        migrations.RemoveField(
            model_name='shipmentrequestmanifest',
            name='inventory_item',
        ),
        migrations.RemoveField(
            model_name='shipmentrequestmanifest',
            name='shipment_request',
        ),
        migrations.RemoveField(
            model_name='shipmentrequestmanifestlog',
            name='responded_by',
        ),
        migrations.RemoveField(
            model_name='shipmentrequestmanifestlog',
            name='shipment_request_manifest',
        ),
        migrations.AddField(
            model_name='shipmentrequest',
            name='is_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ShipmentRequestManifest',
        ),
        migrations.DeleteModel(
            name='ShipmentRequestManifestLog',
        ),
    ]
