# Generated by Django 2.1 on 2018-08-19 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0004_auto_20180819_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='center',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='inventoryitemstock',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='inventoryitemstocklog',
            old_name='modified_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
