# Generated by Django 2.1 on 2018-08-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0005_auto_20180819_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='center',
            name='district_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplies_tracker.Center'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('FD', 'Food'), ('ME', 'Medicine'), ('CL', 'Clothes'), ('OT', 'Other')], max_length=2),
        ),
    ]
