# Generated by Django 2.1 on 2018-08-19 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0007_auto_20180820_0025'),
        ('supplies_tracker', '0007_auto_20180819_2359'),
    ]

    operations = [
    ]
