# Generated by Django 2.1 on 2018-08-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0008_auto_20180820_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='center',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='center',
            field=models.ManyToManyField(blank=True, null=True, to='supplies_tracker.Center'),
        ),
    ]
