# Generated by Django 2.1 on 2018-08-19 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_tracker', '0009_auto_20180820_0118'),
        ('supplies_tracker', '0009_auto_20180820_0101'),
    ]

    operations = [
    ]
